version: '3'
services:
  mysql:
    image: mysql:5.7.13
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: mysql -uroot -ptest -e "SELECT 1"
      interval: 1s
      timeout: 10s
      retries: 10